version: "3.8"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${DOCKER_ROOTPUID:-1000}
      - PGID=${DOCKER_ROOTPGID:-1000}
      - TZ=${TZ:-Europe/Madrid}
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/sonarr:/config
      - ${DOCKER_PATH_MEDIA}/Series:/tv
      - ${DOCKER_PATH_MEDIA}/Descargas/Series:/downloads
    networks:
      - infra_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

networks:
  infra_net:
    external: true
