version: "3.8"

services:
  broker:
    image: 'docker.io/library/redis:7'
    restart: unless-stopped
    volumes:
      - '${DOCKER_PATH_PERSISTENT}/paperless/redisdata:/data'
    networks:
      - infra_net

  db:
    image: 'docker.io/library/postgres:16'
    restart: unless-stopped
    volumes:
      - '${DOCKER_PATH_PERSISTENT}/paperless/postgresql:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASS}'
    networks:
      - infra_net

  webserver:
    image: 'ghcr.io/paperless-ngx/paperless-ngx:latest'
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - '8010:8000'
    volumes:
      - '${DOCKER_PATH_PERSISTENT}/paperless/data:/usr/src/paperless/data'
      - '${DOCKER_PATH_PERSISTENT}/paperless/media:/usr/src/paperless/media'
      - '${DOCKER_PATH_PERSISTENT}/paperless/export:/usr/src/paperless/export'
      - '${DOCKER_PATH_PERSISTENT}/paperless/consume:/usr/src/paperless/consume'
      - '${DOCKER_PATH_TEMPORARY}/paperless/tmp:/tmp/paperless'
      - '${DOCKER_PATH_TEMPORARY}/paperless/logs:/usr/src/paperless/logs'
    environment:
      TZ: ${DOCKER_TZ}
      PUID: 1
      PGID: 1
      PAPERLESS_DBHOST: 'db'
      PAPERLESS_REDIS: 'redis://broker:6379'
      PAPERLESS_ADMIN_USER: ${PAPER_USER}
      PAPERLESS_ADMIN_PASSWORD: ${APP_KEY}
      PAPERLESS_SECRET_KEY: ${APP_KEY}
      PAPERLESS_URL: 'https://paperless.media.local'
      PAPERLESS_ALLOWED_HOSTS: 'paperless.media.local,localhost,127.0.0.1,192.168.1.151'
      PAPERLESS_CSRF_TRUSTED_ORIGINS: 'https://paperless.media.local'
      SESSION_COOKIE_SECURE: 'true'
      CSRF_COOKIE_SECURE: 'true'
      SECURE_PROXY_SSL_HEADER: 'HTTP_X_FORWARDED_PROTO,https'
      PAPERLESS_SCRATCH_DIR: '/tmp/paperless'
      PAPERLESS_LOGLEVEL: 'info'
      PAPERLESS_GMAIL_OAUTH_CLIENT_ID: ${PAPERLESS_GMAIL_OAUTH_CLIENT_ID}
      PAPERLESS_GMAIL_OAUTH_CLIENT_SECRET: ${PAPERLESS_GMAIL_OAUTH_CLIENT_SECRET}
      PAPERLESS_URL: ${PAPERLESS_URL}
    networks:
      - infra_net

volumes:
  data:
  media:
  pgdata:
  redisdata:

networks:
  infra_net:
    external: true


