version: "3.8"

services:
  broker:
    image: 'docker.io/library/redis:7'
    restart: unless-stopped
    volumes:
      - '${DOCKER_PATH_PERSISTENT}/paperless/redisdata:/data'
    networks:
      - infra_net

  db:
    image: 'docker.io/library/postgres:16'
    restart: unless-stopped
    volumes:
      - '${DOCKER_PATH_PERSISTENT}/paperless/postgresql:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASS}'
    networks:
      - infra_net

  webserver:
    image: 'ghcr.io/paperless-ngx/paperless-ngx:latest'
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - '8010:8000'
    volumes:
      - '${DOCKER_PATH_PERSISTENT}/paperless/data:/usr/src/paperless/data'
      - '${DOCKER_PATH_PERSISTENT}/paperless/media:/usr/src/paperless/media'
      - '${DOCKER_PATH_PERSISTENT}/paperless/export:/usr/src/paperless/export'
      - '${DOCKER_PATH_PERSISTENT}/paperless/consume:/usr/src/paperless/consume'
    environment:
      TZ: ${DOCKER_TZ}
      PUID: 1
      PGID: 1
      PAPERLESS_DBHOST: 'db'
      PAPERLESS_REDIS: 'redis://broker:6379'
      PAPERLESS_ADMIN_USER: ${PAPER_USER}
      PAPERLESS_ADMIN_PASSWORD: ${APP_KEY}
    networks:
      - infra_net

volumes:
  data:
  media:
  pgdata:
  redisdata:

networks:
  infra_net:
    external: true
