# - Run 'docker compose pull'.
# - Run 'docker compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker compose up -d'.
services:
  broker:
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}broker-paperless
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/paperless/redisdata:/data

  db:
    image: docker.io/library/mariadb:11
    restart: unless-stopped
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/paperless/dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: $MARIADB_DATABASE
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8004:8000"
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/paperless/data:/usr/src/paperless/data
      - ${DOCKER_PATH_PERSISTENT}/paperless/media:/usr/src/paperless/media
      - ${DOCKER_PATH_PERSISTENT}/paperless/export:/usr/src/paperless/export
      - ${DOCKER_PATH_PERSISTENT}/paperless/consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: $MARIADB_USER # only needed if non-default username
      PAPERLESS_DBPASS: $MARIADB_PASSWORD # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:4000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  dbdata:
  redisdata: