version: "3.8"

services:
  baikal:
    image: ckulka/baikal
    ports:
      - "${DOCKER_BAIKAL_PORT:-8800}:80"
    environment:
      - TZ=${TZ:-Europe/Madrid}
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/baikal/config:/var/www/baikal/Specific
      - ${DOCKER_PATH_PERSISTENT}/baikal/data:/var/www/baikal/baikal-data
    networks:
      - infra_net

networks:
  infra_net:
    external: true
