version: "3.4"

services:
  baikal:
    image: ckulka/baikal
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}baikal
    ports:
      - "${DOCKER_BAIKAL_PORT:-8800}:80"
    environment:
      - TZ=${TZ:-Europe/Madrid}
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/baikal/config:/var/www/baikal/Specific
      - ${DOCKER_PATH_PERSISTENT}/baikal/data:/var/www/baikal/baikal-data
    restart: unless-stopped
