version: "3.8"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1
      - PGID=1
      - TZ=${DOCKER_TZ}
      - SERVERPORT=51820
      - PEERS=10
      - PEERDNS=auto
      - INTERNAL_SUBNET=192.168.0.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/wireward/config:/config
      - ${DOCKER_PATH_PERSISTENT}/wireward/modules:/lib/modules
    restart: always
    ports:
      # Port for WireGuard-UI
      - "5000:5000"
      # Port of the WireGuard VPN server
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
