version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}wireguard
    #network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1
      - PGID=1
      - TZ=${DOCKER_TZ}
      - SERVERPORT=51820
      - PEERS=5
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/wireward/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
