version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}wireguard
    #network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1
      - PGID=1
      - TZ=${DOCKER_TZ}
      - SERVERPORT=51820
      - SERVERURL=bjxtreme.duckdns.org
      - PEERS=5
      - LOG_CONFS=true
      #- PEERDNS=192.168.1.1
      - INTERNAL_SUBNET=192.168.1.1
      #- ALLOWEDIPS=0.0.0.0/0
      - ALLOWEDIPS=192.168.1.1/24
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/wireward/config:/config
      - ${DOCKER_PATH_PERSISTENT}/wireward/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
