version: "3.8"

services:
  jackett:
    image: lscr.io/linuxserver/jackett
    environment:
      - PUID=${DOCKER_ROOTPUID:-1000}
      - PGID=${DOCKER_ROOTPGID:-1000}
      - TZ=${TZ:-Europe/Madrid}
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/jackett:/config
      - ${DOCKER_PATH_MEDIA}/Descargas:/downloads
    ports:
      - target: 9117
        published: 9117
        protocol: tcp
        mode: host
    networks:
      - infra_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

networks:
  infra_net:
    external: true
