version: "3.8"

services:
  plex:
    image: linuxserver/plex
    environment:
      - PUID=${DOCKER_ROOTPUID:-1}
      - PGID=${DOCKER_ROOTPGID:-1}
      - VERSION=docker
      - TZ=${TZ:-Europe/Madrid}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/plex/config:/config
      - ${DOCKER_PATH_MEDIA}/Peliculas:/media/movies
      - ${DOCKER_PATH_MEDIA}/Series:/media/tv
      - ${DOCKER_PATH_MEDIA}/Musica:/media/music
    networks:
      - infra_net
    ports:
      - target: 32400
        published: 32400
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  infra_net:
    external: true
