version: "2.1"

services:
  home-assistant:
    image: homeassistant/home-assistant:stable
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}home-assistant
    hostname: home-assistant
    mac_address: ${DOCKER_CONTAINER_MAC}
    healthcheck:
      test: "curl -Lk -fsS http://localhost:8123 || exit 1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_PATH_PERSISTENT}/homeassistant/config:/config:rw
      - ${DOCKER_PATH_TEMPORARY}/homeassistant/tmp:/tmp:rw
    restart: always
    networks:
      macvlan0:
        ipv4_address: ${DOCKER_IPV4}
    environment:
      - TZ=${DOCKER_TZ}
networks:
  domotica_macvlan0:
    external: true

#networks:
#  macvlan0:
#    driver: macvlan
#    driver_opts:
#      parent: ${LAN_INTERFACE} #**Your network interface for example enp6s1 
#    ipam:
#      config:
#        - subnet: ${LAN_SUBNET}     #**Your network subnet for example 192.168.0.0/16
#          gateway: ${LAN_GATEWAY}   #**Your network gateway for example 192.168.1.1
