version: "3.8"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=${DOCKER_ROOTPUID:-1000}
      - PGID=${DOCKER_ROOTPGID:-1000}
      - TZ=${TZ:-Europe/Madrid}
      - WEBUI_PORT=8091
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/qbittorrent:/config
      - ${DOCKER_PATH_MEDIA}/Descargas/Series:/downloads
    networks:
      - infra_net
    ports:
      - target: 8091
        published: 8091
        protocol: tcp
        mode: host
      - target: 6881
        published: 6881
        protocol: tcp
        mode: host
      - target: 6881
        published: 6881
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == debian12
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

networks:
  infra_net:
    external: true
