version: "3.8"

services:
  netshoot:
    image: nicolaka/netshoot
    command: tail -f /dev/null
    networks:
      - media_net

networks:
  media_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
