version: "3.8"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}adguardhome
    hostname: ${ADGUARD_HOSTNAME:-adguardhome}
    restart: unless-stopped

    environment:
      TZ: ${DOCKER_TZ:-Europe/Madrid}

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:80 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      domotica_macvlan0:
        ipv4_address: ${DOCKER_IPV4}

    volumes:
      - ${ADGUARD_WORK_PATH}:/opt/adguardhome/work:rw
      - ${ADGUARD_CONFIG_PATH}:/opt/adguardhome/conf:rw
      - ${TRAEFIK_CERTS_PATH}:/opt/adguardhome/certs:ro

networks:
  domotica_macvlan0:
    external: true
