version: "3.8"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX:-}adguardhome
    hostname: ${ADGUARD_HOSTNAME:-adguardhome}
    restart: unless-stopped

    environment:
      TZ: ${DOCKER_TZ:-Europe/Madrid}

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:80 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      domotica_macvlan0:
        ipv4_address: ${DOCKER_IPV4:?DOCKER_IPV4 is required}

    volumes:
      - ${DOCKER_PATH_TEMPORARY}/${ADGUARD_WORK_DIR:?ADGUARD_WORK_DIR is required}:/opt/adguardhome/work:rw
      - ${DOCKER_PATH_PERSISTENT}/${ADGUARD_CONFIG_DIR:?ADGUARD_CONFIG_DIR is required}:/opt/adguardhome/conf:rw
      - ${DOCKER_PATH_TEMPORARY}/traextor_certs:/opt/adguardhome/certs:ro

networks:
  domotica_macvlan0:
    external: true
