version: "3.8"

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    environment:
      - PUID=${DOCKER_ROOTPUID}
      - PGID=${DOCKER_ROOTPGID}
      - TZ=${DOCKER_TZ}
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/zigbee2mqtt/data:/app/data
      - ${DOCKER_PATH_PERSISTENT}/zigbee2mqtt/run/udev:/run/udev:ro
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/ttyUSB0
    ports:
      - 8080:8080
    user: 0:0
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z -w3 192.168.1.151 1883 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    cap_add:
      - SYS_TTY_CONFIG
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 60s
