version: "3.8"

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest

    environment:
      TZ: ${DOCKER_TZ}

    user: "${DOCKER_ROOTPUID:-1000}:${DOCKER_ROOTPGID:-1000}"

    volumes:
      - type: bind
        source: ${DOCKER_PATH_PERSISTENT}/zigbee2mqttzlzb/data
        target: /app/data

      - type: bind
        source: ${DOCKER_PATH_TEMPORARY}/zigbee2mqttzlzb/run/udev
        target: /run/udev
        read_only: true

      - type: bind
        source: ${DOCKER_PATH_PERSISTENT}/zigbee2mqttzlzb/log
        target: /app/log

    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

    healthcheck:
      test: ["CMD", "/usr/bin/wget", "-q", "-O", "-", "http://127.0.0.1:8080"]
      interval: 60s
      timeout: 5s
      retries: 6
      start_period: 30s

    networks:
      - infra_net

    deploy:
      mode: replicated
      replicas: 1

      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME}

      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 0
        window: 120s

      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
        monitor: 30s

      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first

      resources:
        reservations:
          cpus: "${ZIGBEE2MQTT_RES_CPU}"
          memory: ${ZIGBEE2MQTT_RES_MEM}
        limits:
          cpus: "${ZIGBEE2MQTT_LIM_CPU}"
          memory: ${ZIGBEE2MQTT_LIM_MEM}

      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=infra_net"
        - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee-avila.media.local`)"
        - "traefik.http.routers.zigbee2mqtt.entrypoints=https"
        - "traefik.http.routers.zigbee2mqtt.tls=true"
        - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"
        - "com.centurylinklabs.watchtower.scope=swarm"

networks:
  infra_net:
    external: true
    name: ${DOCKER_NETWORK:-infra_net}
