version: "3.8"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${DOCKER_ROOTPUID:-1000}
      - PGID=${DOCKER_ROOTPGID:-1000}
      - TZ=${TZ:-Europe/Madrid}
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/radarr:/config
      - ${DOCKER_PATH_MEDIA}/Peliculas:/movies
      - ${DOCKER_PATH_MEDIA}/Descargas/Series:/downloads
    ports:
      - 7878:7878
    networks:
      - infra_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

networks:
  infra_net:
    external: true
