version: "3.8"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest

    environment:
      - PUID=${DOCKER_ROOTPUID:-1000}
      - PGID=${DOCKER_ROOTPGID:-1000}
      - TZ=${DOCKER_TZ}

    volumes:
      - ${DOCKER_PATH_PERSISTENT}/radarr:/config
      - ${DOCKER_PATH_MEDIA}/Peliculas:/movies
      - ${DOCKER_PATH_MEDIA}/Descargas/Series:/downloads

    ports:
      - target: 7878
        published: ${RADARR_EXTERNAL_PORT:-7878}
        protocol: tcp
        mode: ingress

    networks:
      - infra_net

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:7878/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    deploy:
      mode: replicated
      replicas: 1

      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME}

      restart_policy:
        condition: any
        delay: 10s
        window: 120s

      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
        monitor: 30s

      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first

      resources:
        reservations:
          cpus: "${RADARR_RES_CPU:-0.25}"
          memory: ${RADARR_RES_MEM:-256M}
        limits:
          cpus: "${RADARR_LIM_CPU:-1.00}"
          memory: ${RADARR_LIM_MEM:-1G}

      labels:
        - "com.centurylinklabs.watchtower.scope=swarm"

        - "traefik.enable=true"
        - "traefik.swarm.network=infra_net"

        - "traefik.http.routers.${STACK_KEY}-http.rule=Host(`${RADARR_HOST}`)"
        - "traefik.http.routers.${STACK_KEY}-http.entrypoints=http"
        - "traefik.http.routers.${STACK_KEY}-http.middlewares=redirect-to-https@file"
        - "traefik.http.routers.${STACK_KEY}-http.service=noop@internal"

        - "traefik.http.routers.${STACK_KEY}-https.rule=Host(`${RADARR_HOST}`)"
        - "traefik.http.routers.${STACK_KEY}-https.entrypoints=https"
        - "traefik.http.routers.${STACK_KEY}-https.tls.certresolver=step"
        - "traefik.http.routers.${STACK_KEY}-https.service=${STACK_KEY}-svc"

        - "traefik.http.services.${STACK_KEY}-svc.loadbalancer.server.port=7878"

networks:
  infra_net:
    external: true
