version: "3.8"

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:3.3.20
    environment:
      - LOG_LEVEL=debug
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ:-Europe/Madrid}
      - HEADLESS=true
      - LANG=es-ES
    ports:
      - 8191:8191
    networks:
      - infra_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    dns:
      - 1.1.1.1
      - 8.8.8.8
    shm_size: "2gb"
networks:
  infra_net:
    external: true
