version: "3.8"

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    environment:
      - PUID=${DOCKER_ROOTPUID:-1000}
      - PGID=${DOCKER_ROOTPGID:-1000}
      - TZ=${TZ:-Europe/Madrid}
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/bazarr:/config
      - ${DOCKER_PATH_MEDIA}:/media
    networks:
      - infra_net
    ports:
      - target: 6767
        published: 6767
        protocol: tcp
        mode: host

networks:
  infra_net:
    external: true
