version: "3.9"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    hostname: filebrowser
    restart: always

    ports:
      - target: ${FILEBROWSER_INTERNAL_PORT:-80}
        published: ${FILEBROWSER_EXTERNAL_PORT:-8086}
        protocol: tcp
        mode: ingress

    volumes:
      - ${DOCKER_PATH_PERSISTENT}:/data/docker
      - ${DOCKER_PATH_TEMPORARY}:/data/docker-logs
      - ${DOCKER_PATH_PERSISTENT}/filebrowser/config:/config:rw
      - ${DOCKER_PATH_PERSISTENT}/filebrowser/database:/database:rw

    environment:
      - PUID=${DOCKER_ROOTPUID:-1000}
      - PGID=${DOCKER_ROOTPGID:-1000}
      - TZ=${DOCKER_TZ}
      - FB_USER=${FILEBROWSER_USER:-admin}
      - FB_PASS=${FILEBROWSER_PASS:-admin123}

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:${FILEBROWSER_INTERNAL_PORT:-80}/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 5

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      labels:
        - "com.centurylinklabs.watchtower.scope=swarm"

    networks:
      - infra_net

networks:
  infra_net:
    external: true
