version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    hostname: filebrowser
    restart: always
    ports:
      - 8086:80
    volumes:
      - ${DOCKER_PATH_PERSISTENT}:/data/docker
      - ${DOCKER_PATH_TEMPORARY}:/data/docker-logs
      - ${DOCKER_PATH_PERSISTENT}/filebrowser/config:/config:rw
      - ${DOCKER_PATH_PERSISTENT}/filebrowser/database:/database:rw
    environment:
      - PUID=${DOCKER_ROOTPUID:-1}
      - PGID=${DOCKER_ROOTPGID:-27}
      - TZ=${DOCKER_TZ}
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - infra_net

networks:
  infra_net:
    external: true
