version: "3.9"

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    hostname: filebrowser
    restart: always

    ports:
      - target: ${FILEBROWSER_INTERNAL_PORT:-80}
        published: ${FILEBROWSER_EXTERNAL_PORT:-8086}
        protocol: tcp
        mode: ingress

    volumes:
      - ${DOCKER_PATH_PERSISTENT}:/data/docker
      - ${DOCKER_PATH_TEMPORARY}:/data/docker-logs
      - ${DOCKER_PATH_PERSISTENT}/filebrowser/config:/config:rw
      - ${DOCKER_PATH_PERSISTENT}/filebrowser/database:/database:rw

    environment:
      - TZ=${DOCKER_TZ}
      - PUID=${DOCKER_ROOTPUID:-1000}
      - PGID=${DOCKER_ROOTPGID:-1000}
      - FB_ROOT=/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${FILEBROWSER_INTERNAL_PORT:-80}/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

    deploy:
      mode: replicated
      replicas: 1

      restart_policy:
        condition: any
        delay: 10s
        window: 120s

      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
        monitor: 30s

      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        
      resources:
        reservations:
          cpus: "${FILEBROWSER_RES_CPU}"
          memory: ${FILEBROWSER_RES_MEM}
        limits:
          cpus: "${FILEBROWSER_LIM_CPU}"
          memory: ${FILEBROWSER_LIM_MEM}
        
      labels:
        - "com.centurylinklabs.watchtower.scope=swarm"

        - "traefik.enable=true"
        - "traefik.swarm.network=infra_net"
        
        - "traefik.http.routers.${STACK_KEY}-http.rule=Host(`${FILEBROWSER_HOST}`)"
        - "traefik.http.routers.${STACK_KEY}-http.entrypoints=http"
        - "traefik.http.routers.${STACK_KEY}-http.middlewares=redirect-to-https@file"
        - "traefik.http.routers.${STACK_KEY}-http.service=noop@internal"

        - "traefik.http.routers.${STACK_KEY}-https.rule=Host(`${FILEBROWSER_HOST}`)"
        - "traefik.http.routers.${STACK_KEY}-https.entrypoints=https"
        - "traefik.http.routers.${STACK_KEY}-https.tls.certresolver=step"
        - "traefik.http.routers.${STACK_KEY}-https.service=${STACK_KEY}-svc"

        - "traefik.http.services.${STACK_KEY}-svc.loadbalancer.server.port=${FILEBROWSER_INTERNAL_PORT:-80}"

    networks:
      - infra_net

networks:
  infra_net:
    external: true
