version: "2.1"

services:
  filebrowser:
    pull_policy: always
    user: root
    image: 	filebrowser/filebrowser:stable
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}filebrowser
    hostname: filebrowser
    restart: always
    network_mode: bridge
    ports:
      - 8086:80
    volumes:
      - ${DOCKER_PATH_PERSISTENT}:/data/docker
      - ${DOCKER_PATH_TEMPORARY}:/data/docker-logs
      - ${DOCKER_PATH_PERSISTENT}/filebrowser/config:/config:rw
      - ${DOCKER_PATH_PERSISTENT}/filebrowser/database:/database:rw
    environment:
      - PUID=${DOCKER_ROOTPUID:-0}
      - PGID=${DOCKER_ROOTPGID:-0}
      - TZ=${DOCKER_TZ}
