version: '3'
services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: "host"
    environment:
      - USERNAME=${ESP_USER}
      - PASSWORD=${ESP_PASS}
  mdns-repeater:
    image: monstrenyatko/mdns-repeater
    container_name: mdns-repeater
    restart: unless-stopped
    command: mdns-repeater-app -f ens18 ens18 #eg mdns-repeater-app -f eth0 br-abcdefghijk
    network_mode: "host"
