version: "3.9"

services:
  ring-mqtt:
    image: tsightler/ring-mqtt:latest

    environment:
      TZ: ${DOCKER_TZ}

    volumes:
      - ${DOCKER_PATH_PERSISTENT}/ring-mqtt/data:/data:rw

    ports:
      - target: 8554
        published: ${RING_MQTT_RTSP_PORT:-8554}
        protocol: tcp
        mode: host

    networks:
      - infra_net

    healthcheck:
      test: ["CMD-SHELL", "test -s /data/config.json || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    deploy:
      mode: replicated
      replicas: 1

      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME}

      restart_policy:
        condition: any
        delay: 10s
        window: 120s

      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
        monitor: 30s

      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first

      resources:
        reservations:
          cpus: "${RING_MQTT_RES_CPU}"
          memory: ${RING_MQTT_RES_MEM}
        limits:
          cpus: "${RING_MQTT_LIM_CPU}"
          memory: ${RING_MQTT_LIM_MEM}

      labels:
        - "com.centurylinklabs.watchtower.scope=swarm"

networks:
  infra_net:
    external: true
    name: ${DOCKER_NETWORK:-infra_net}
