version: "3.8"

services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      - "1884:1884"  # Para MQTT TCP
      - "1885:1885"  # Para MQTT TCP
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_PATH_PERSISTENT}/traefik/acme:/letsencrypt
    configs:
      - source: traefik_static_config
        target: /etc/traefik/traefik.yml
      - source: traefik_dynamic_config
        target: /etc/traefik/dynamic.yml
    secrets:
      - media_local_crt
      - media_local_key
    networks:
      - infra_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  infra_net:
    external: true

configs:
  traefik_static_config:
    external: true
  traefik_dynamic_config:
    external: true

secrets:
  media_local_crt:
    external: true
  media_local_key:
    external: true
