services:
  mosquitto:
    image: eclipse-mosquitto:latest
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/mosquitto${MOSQ_SUFFIX:-}/config:/mosquitto/config
      - ${DOCKER_PATH_PERSISTENT}/mosquitto${MOSQ_SUFFIX:-}/data:/mosquitto/data:rw
      - ${DOCKER_PATH_TEMPORARY}/mosquitto${MOSQ_SUFFIX:-}/log:/mosquitto/log:rw
    networks:
      - infra_net
    ports:
      - target: ${MOSQ_PORT_INTERNAL:-1883}
        published: ${MOSQ_PORT:-1883}
        protocol: tcp
        mode: host
      - target: ${MOSQ_WS_PORT_INTERNAL:-9001}
        published: ${MOSQ_WS_PORT:-9001}
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: any
networks:
  infra_net:
    external: true





