version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}mosquitto-local
    environment:
      - TZ=Europe/Madrid    
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/mosquitto/config:/mosquitto/config
      - ${DOCKER_PATH_PERSISTENT}/mosquitto/data:/mosquitto/data:rw
      - ${DOCKER_PATH_TEMPORARY}/mosquitto/log:/mosquitto/log:rw
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped