version: "3.9"

services:
  homer:
    image: b4bz/homer:latest
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/homer2/assets:/www/assets
    networks:
      - infra_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME}

      mode: replicated

      restart_policy:
        condition: any
        delay: 10s
        window: 120s

      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
        monitor: 30s

      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first

      resources:
        reservations:
          cpus: "${HOMER_RES_CPU}"
          memory: ${HOMER_RES_MEM}
        limits:
          cpus: "${HOMER_LIM_CPU}"
          memory: ${HOMER_LIM_MEM}
          
      labels:
        - traefik.enable=true
        - traefik.swarm.network=infra_net

        - traefik.http.routers.${STACK_KEY}-http.rule=Host(`${HOMER_HOST}`)
        - traefik.http.routers.${STACK_KEY}-http.entrypoints=http
        - traefik.http.routers.${STACK_KEY}-http.middlewares=redirect-to-https@file
        - traefik.http.routers.${STACK_KEY}-http.service=noop@internal

        - traefik.http.routers.${STACK_KEY}-https.rule=Host(`${HOMER_HOST}`)
        - traefik.http.routers.${STACK_KEY}-https.entrypoints=https
        - traefik.http.routers.${STACK_KEY}-https.tls.certresolver=step
        - traefik.http.routers.${STACK_KEY}-https.service=${STACK_KEY}-svc

        - traefik.http.services.${STACK_KEY}-svc.loadbalancer.server.port=8080

        - com.centurylinklabs.watchtower.scope=swarm

networks:
  infra_net:
    external: true
