version: "3.8"

services:
  ytdl-material:
    image: tzahi12345/youtubedl-material:latest
    container_name: ytdl-material
    ports:
      - "8998:17442"
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/yt-dlp/downloads:/app/video
      - ${DOCKER_PATH_PERSISTENT}/yt-dlp/audio:/app/audio
      - ${DOCKER_PATH_PERSISTENT}/yt-dlp/subscriptions:/app/subscriptions
      - ${DOCKER_PATH_PERSISTENT}/yt-dlp/users:/app/users
      - ${DOCKER_PATH_PERSISTENT}/yt-dlp/config:/app/appdata
    environment:
      - ytdl_mongodb_connection_string=mongodb://mongo:27017
      - ALLOW_CONFIG_MUTATIONS=true
      - TZ=Europe/Madrid
    depends_on:
      - mongo
    networks:
      - infra_net
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: ytdl-mongo
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/mongo-data:/data/db
    networks:
      - infra_net
    restart: unless-stopped

networks:
  infra_net:
    external: true
