version: "3.8"

services:
  downloader:
    image: ghcr.io/axel669/yt-dlp:latest
    container_name: yt-downloader
    entrypoint: tail -f /dev/null  # Mantiene el contenedor vivo esperando comandos
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/yt-dlp/downloads:/downloads
    networks:
      - infra_net
    restart: unless-stopped

networks:
  infra_net:
    external: true
